/*
 * Beam game development API
 *
 * The Beam game development API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Beam.Client.FileParameter;
using OpenAPIDateConverter = Beam.Client.OpenAPIDateConverter;

namespace Beam.Model
{
    /// <summary>
    /// GetProfileAssetsFilterParameter
    /// </summary>
    [DataContract(Name = "getProfileAssets_filter_parameter")]
    public partial class GetProfileAssetsFilterParameter : IEquatable<GetProfileAssetsFilterParameter>, IValidatableObject
    {
        /// <summary>
        /// Defines SellTypes
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SellTypesEnum
        {
            /// <summary>
            /// Enum AscendingAuction for value: AscendingAuction
            /// </summary>
            [EnumMember(Value = "AscendingAuction")]
            AscendingAuction = 1,

            /// <summary>
            /// Enum DescendingAuction for value: DescendingAuction
            /// </summary>
            [EnumMember(Value = "DescendingAuction")]
            DescendingAuction = 2,

            /// <summary>
            /// Enum FixedPrice for value: FixedPrice
            /// </summary>
            [EnumMember(Value = "FixedPrice")]
            FixedPrice = 3,

            /// <summary>
            /// Enum NotForSale for value: NotForSale
            /// </summary>
            [EnumMember(Value = "NotForSale")]
            NotForSale = 4
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GetProfileAssetsFilterParameter" /> class.
        /// </summary>
        /// <param name="attributes">attributes.</param>
        /// <param name="sellTypes">sellTypes.</param>
        public GetProfileAssetsFilterParameter(List<GetProfileAssetsFilterParameterAttributesInner> attributes = default(List<GetProfileAssetsFilterParameterAttributesInner>), List<SellTypesEnum> sellTypes = default(List<SellTypesEnum>))
        {
            this.Attributes = attributes;
            this.SellTypes = sellTypes;
        }

        /// <summary>
        /// Gets or Sets Attributes
        /// </summary>
        [DataMember(Name = "attributes", EmitDefaultValue = true)]
        public List<GetProfileAssetsFilterParameterAttributesInner> Attributes { get; set; }

        /// <summary>
        /// Gets or Sets SellTypes
        /// </summary>
        [DataMember(Name = "sellTypes", EmitDefaultValue = true)]
        public List<GetProfileAssetsFilterParameter.SellTypesEnum> SellTypes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetProfileAssetsFilterParameter {\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  SellTypes: ").Append(SellTypes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetProfileAssetsFilterParameter);
        }

        /// <summary>
        /// Returns true if GetProfileAssetsFilterParameter instances are equal
        /// </summary>
        /// <param name="input">Instance of GetProfileAssetsFilterParameter to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetProfileAssetsFilterParameter input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Attributes == input.Attributes ||
                    this.Attributes != null &&
                    input.Attributes != null &&
                    this.Attributes.SequenceEqual(input.Attributes)
                ) && 
                (
                    this.SellTypes == input.SellTypes ||
                    this.SellTypes != null &&
                    input.SellTypes != null &&
                    this.SellTypes.SequenceEqual(input.SellTypes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Attributes != null)
                {
                    hashCode = (hashCode * 59) + this.Attributes.GetHashCode();
                }
                if (this.SellTypes != null)
                {
                    hashCode = (hashCode * 59) + this.SellTypes.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
