/*
 * Beam game development API
 *
 * The Beam game development API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Beam.Client.OpenAPIDateConverter;

namespace Beam.Model
{
    /// <summary>
    /// UpdateProfileRequestInput
    /// </summary>
    [DataContract(Name = "UpdateProfileRequestInput")]
    public partial class UpdateProfileRequestInput : IEquatable<UpdateProfileRequestInput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateProfileRequestInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateProfileRequestInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateProfileRequestInput" /> class.
        /// </summary>
        /// <param name="newProfileId">newProfileId (required).</param>
        public UpdateProfileRequestInput(string newProfileId = default(string))
        {
            // to ensure "newProfileId" is required (not null)
            if (newProfileId == null)
            {
                throw new ArgumentNullException("newProfileId is a required property for UpdateProfileRequestInput and cannot be null");
            }
            this.NewProfileId = newProfileId;
        }

        /// <summary>
        /// Gets or Sets NewProfileId
        /// </summary>
        [DataMember(Name = "newProfileId", IsRequired = true, EmitDefaultValue = true)]
        public string NewProfileId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateProfileRequestInput {\n");
            sb.Append("  NewProfileId: ").Append(NewProfileId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateProfileRequestInput);
        }

        /// <summary>
        /// Returns true if UpdateProfileRequestInput instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateProfileRequestInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateProfileRequestInput input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.NewProfileId == input.NewProfileId ||
                    (this.NewProfileId != null &&
                    this.NewProfileId.Equals(input.NewProfileId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NewProfileId != null)
                {
                    hashCode = (hashCode * 59) + this.NewProfileId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
